spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      channels:
        calculations_channel:
          name: calculations_channel

  servlet:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 50MB
      max-request-size: 100MB

  cloud:
    aws:
      s3:
        endpoint: http://127.0.0.1:9000
        bucket: corpbucket
      credentials:
        access-key: user
        secret-key: password
      region:
        static: eu-central-1


server:
  port: 8087

logging:
  level:
    root: info

file:
  upload:
    max-size: 5242880

user-service:
  host: localhost
  port: 8080
post-service:
  host: localhost
  port: 8081
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
url-shortener-service:
  host: localhost
  port: 8080
